### ISSUE TITLE
Bug bunny weird css (overlapsing)

### ISSUE THREAD

**Issue by Virginie-T** [tasminions/minionchat#36]
<img width="714" alt="screen shot 2016-02-26 at 10 43 45 am" src="https://cloud.githubusercontent.com/assets/8175545/13350129/178fbbcc-dc76-11e5-9e20-62740d0e1bdf.png">

**Comment by eleanorreem** [comment]
it doesnt work yet! hopefully will get it working by his evening

**Comment by franzmoro** [comment]
should be working now. unfortunately there was no specific commit.
